services:
  # -------------------------
  # .NET App
  # -------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      ConnectionStrings__OTLP_ENDPOINT: "http://alloy:4317"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      alloy:
        condition: service_started
      redis:
        condition: service_healthy

  # -------------------------
  # Redis Cache for Metrics
  # -------------------------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # -------------------------
  # Redis Exporter with Custom Lua Script
  # -------------------------
  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
    volumes:
      - ./configs/redis-exporter.lua:/app/redis-exporter.lua:ro
    command: |
      sh -c "
        redis_exporter \
          -redis.addr=redis:6379 \
          -web.listen-address=:9121 \
          -web.telemetry-path=/metrics \
          -script=/app/redis-exporter.lua \
          -log-format=txt
      "
    depends_on:
      - redis

  # -------------------------
  # Grafana Alloy (OTEL Collector)
  # -------------------------
  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # Alloy UI
    volumes:
      - ./configs/alloy.hcl:/etc/alloy/config.alloy
    command: [ "run", "/etc/alloy/config.alloy" ]

  # -------------------------
  # Prometheus
  # -------------------------
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.wal-compression'
      - '--storage.remote.flush-deadline=10s'
      - '--storage.remote.read-concurrent-limit=20'
    depends_on:
      - alloy

  # -------------------------
  # Loki
  # -------------------------
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  # -------------------------
  # Grafana
  # -------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki

volumes:
  grafana-storage:
  redis-data:
