global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

remote_write:
  - url: "http://localhost:9090/api/v1/write"
    queue_config:
      capacity: 10000
      max_shards: 50
      min_shards: 1
      max_samples_per_send: 5000
      batch_send_deadline: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
